### ISSUE TITLE
GitHub Packages Registry?

### ISSUE THREAD

**Issue by fgauna12** [Link-/actions-at-scale-ghoh#1]
Thanks for the work you've put into this. 

I'm curious, any particular reason why using Azure Container Registry over GitHub Packages?

**Comment by Link-** [comment]
Thank you @fgauna12 🙇‍♂️ 

I think both are viable options, however, ACR is closer to the rest of the setup and keeps everything a little bit more homogeneous.

**Comment by fgauna12** [comment]
Got it. I was just wondering if there were some technical reasons. It sounds like there isn't.
