### ISSUE TITLE
Updating the DNS Label Manually

### ISSUE THREAD

**Issue by fgauna12** [Link-/actions-at-scale-ghoh#2]
In the instructions, there's a set of comments like the following. 

```
# !!! IMPORTANT !!!
#
# Add a DNS alias for the public ip manually before proceeding
#
# !!! IMPORTANT !!!
```

From the Azure CLI, when creating a Public IP, you can specify the `--dns-label` so it probably doesn't have to be done manually. 

``` bash
# First create a public IP resource
az network public-ip create \
  --resource-group GitHubActionsRunners \
  --name APGWPublicIp \
  --allocation-method Static \
  --sku Standard \
  --dns-label mydnslabel
```

Happy to open a PR if it helps.

**Comment by Link-** [comment]
That's awesome @fgauna12 !! I'd love contributions on this repo but I'm worried it'll make the instructions not consistent with the videos anymore ☹️

Maybe we could add this step as a comment i.e. as an alternative?

**Comment by fgauna12** [comment]
Oh yeah, that dawned on me when I watched the episode today. That makes sense!

Maybe I'll take a shot at the comment approach.
