### ISSUE TITLE
Pre-requisites section in README?

### ISSUE THREAD

**Issue by fgauna12** [Link-/actions-at-scale-ghoh#3]
I noticed there's no mention of what kind of access is needed for Azure.

I was attempting to follow from an Enterprise sandbox subscription with Contributor rights. I ran into quite a few issues with role assignments. 

Would it be useful to call out a pre-requisites section in the README with the recommended Azure roles?

Maybe it was mentioned in the first video of the series and I missed it.

**Comment by Link-** [comment]
That's a very good point @fgauna12 - It'll be great to document those! Do you have the bandwidth to contribute a PR to the README?

**Comment by Link-** [comment]
Merged
